name: icu_format
description: Dynamically format ICU messages
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-175.0.dev


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
